


/*------ SYSDBA 06/12/2013 11:42:59 --------*/

ALTER TABLE TBCLIENTE
    ADD DESCONTO DMN_MONEY,
    ADD SALDODEBITO DMN_MONEY,
    ADD TABELAPRECO VARCHAR(20),
    ADD SUFRAMA VARCHAR(14),
    ADD COMPLEMENDER VARCHAR(50),
    ADD OBSCLI BLOB SUB_TYPE 1 SEGMENT SIZE 500;




/*------ SYSDBA 06/12/2013 12:37:05 --------*/

CREATE DOMAIN DMN_BOELANO AS
CHAR(1)
CHECK (value in('S','N'));


/*------ SYSDBA 06/12/2013 13:06:13 --------*/

ALTER TABLE TBPRODUTO
    ADD IAT CHAR(1),
    ADD IPPT CHAR(1),
    ADD SITUACAO_TRIB CHAR(1),
    ADD DTESTOQ DMN_DATE,
    ADD FLAGACEITO VARCHAR(3),
    ADD FLAGSIS DMN_BOELANO,
    ADD FLAGEST DMN_BOELANO,
    ADD FLAGCOMBUST DMN_BOELANO,
    ADD PRECO_APRAZO NUMERIC(15,3),
    ADD PRECO2 NUMERIC(15,3),
    ADD FLAGGRADE DMN_BOELANO,
    ADD FLAGBALANCA DMN_BOELANO,
    ADD DTINIPROM DMN_DATE,
    ADD DTFIMPROM DMN_DATE,
    ADD PROD_SERV CHAR(1),
    ADD FLAGATIVO VARCHAR(3),
    ADD DESCONTO_MAX DMN_MONEY,
    ADD FLAGKITPROD DMN_BOELANO,
    ADD FLAGSERIAL DMN_BOELANO,
    ADD TCSMART VARCHAR(30),
    ADD TIPI VARCHAR(8),
    ADD GENERO VARCHAR(8),
    ADD ALIQUOTA_IPI NUMERIC(5,2),
    ADD TPMERCREV VARCHAR(2);

COMMENT ON COLUMN TBPRODUTO.IAT IS
'Indicador de arredondamento ou truncamento(A ou T).
Integracao PAF-ECF';

COMMENT ON COLUMN TBPRODUTO.IPPT IS
'Indicador de produção própia ou de terceiros  ( ''P'' ou ''T'')
Integracao PAF-ECF';

COMMENT ON COLUMN TBPRODUTO.SITUACAO_TRIB IS
'Situação Tributaria (''T'', ''F'', ''I'', ''N'' OU ''S'')
Integracao PAF-ECF';

COMMENT ON COLUMN TBPRODUTO.DTESTOQ IS
'Data do Estoque Veiculos';

COMMENT ON COLUMN TBPRODUTO.FLAGACEITO IS
'Integracao PAF-ECF';

COMMENT ON COLUMN TBPRODUTO.FLAGSIS IS
'Integracao PAF-ECF';

COMMENT ON COLUMN TBPRODUTO.FLAGEST IS
'Integracao PAF-ECF';

COMMENT ON COLUMN TBPRODUTO.FLAGCOMBUST IS
'Integracao PAF-ECF';

COMMENT ON COLUMN TBPRODUTO.PRECO_APRAZO IS
'Integracao PAF-ECF';

COMMENT ON COLUMN TBPRODUTO.PRECO2 IS
'Preco Real de Compra de Veiculos.
Integracao PAF-ECF';

COMMENT ON COLUMN TBPRODUTO.FLAGGRADE IS
'Integracao PAF-ECF';

COMMENT ON COLUMN TBPRODUTO.FLAGBALANCA IS
'Integracao PAF-ECF';

COMMENT ON COLUMN TBPRODUTO.DTINIPROM IS
'Integracao PAF-ECF';

COMMENT ON COLUMN TBPRODUTO.DTFIMPROM IS
'Integracao PAF-ECF';

COMMENT ON COLUMN TBPRODUTO.PROD_SERV IS
'Produto ou Servico (''P'' ou ''S'').
Integracao PAF-ECF';

COMMENT ON COLUMN TBPRODUTO.FLAGATIVO IS
'Integracao PAF-ECF';

COMMENT ON COLUMN TBPRODUTO.DESCONTO_MAX IS
'Integracao PAF-ECF';

COMMENT ON COLUMN TBPRODUTO.FLAGKITPROD IS
'Integracao PAF-ECF. KIT PRODUTOS';

COMMENT ON COLUMN TBPRODUTO.FLAGSERIAL IS
'Integracao PAF-ECF';

COMMENT ON COLUMN TBPRODUTO.TCSMART IS
'Integracao PAF-ECF';

COMMENT ON COLUMN TBPRODUTO.TIPI IS
'Tabela de Incidencias sobre Produtos Industrializados.
Integracao PAF-ECF';

COMMENT ON COLUMN TBPRODUTO.GENERO IS
'Integracao PAF-ECF';

COMMENT ON COLUMN TBPRODUTO.ALIQUOTA_IPI IS
'Aliquota do IPI.
Integracao PAF-ECF';

COMMENT ON COLUMN TBPRODUTO.TPMERCREV IS
'Integracao PAF-ECF';




/*------ SYSDBA 10/12/2013 11:22:56 --------*/

ALTER TABLE TBVENDAS
    ADD SITUACAO CHAR(1) DEFAULT 'S';




/*------ SYSDBA 10/12/2013 16:41:37 --------*/

ALTER TABLE TBPRODUTO
    ADD DESCRIUNID VARCHAR(50);

COMMENT ON COLUMN TBPRODUTO.DESCRIUNID IS
'Integracao PAF-ECF';




/*------ SYSDBA 10/12/2013 16:58:12 --------*/

ALTER TABLE TBVENDAS ADD IBE$$TEMP_COLUMN
 CHAR(1) DEFAULT 'F'
;

UPDATE RDB$RELATION_FIELDS F1
SET
F1.RDB$DEFAULT_VALUE  = (SELECT F2.RDB$DEFAULT_VALUE
                         FROM RDB$RELATION_FIELDS F2
                         WHERE (F2.RDB$RELATION_NAME = 'TBVENDAS') AND
                               (F2.RDB$FIELD_NAME = 'IBE$$TEMP_COLUMN')),
F1.RDB$DEFAULT_SOURCE = (SELECT F3.RDB$DEFAULT_SOURCE FROM RDB$RELATION_FIELDS F3
                         WHERE (F3.RDB$RELATION_NAME = 'TBVENDAS') AND
                               (F3.RDB$FIELD_NAME = 'IBE$$TEMP_COLUMN'))
WHERE (F1.RDB$RELATION_NAME = 'TBVENDAS') AND
      (F1.RDB$FIELD_NAME = 'SITUACAO');

ALTER TABLE TBVENDAS DROP IBE$$TEMP_COLUMN;




/*------ SYSDBA 10/12/2013 16:58:39 --------*/

ALTER TABLE TBVENDAS
    ADD TOTALACRESCIMO DMN_MONEY;




/*------ SYSDBA 10/12/2013 17:10:27 --------*/

ALTER TABLE TBVENDAS
    ADD TOTALDESCONTO DMN_MONEY;

COMMENT ON COLUMN TBVENDAS.TOTALACRESCIMO IS
'Integracao PAF-ECF';

COMMENT ON COLUMN TBVENDAS.TOTALDESCONTO IS
'Integracao PAF-ECF';

