


/*------ SYSDBA 07/05/2014 03:13:46 --------*/

ALTER TABLE TBPRODUTO
    ADD CUST_DESP_OFIC DMN_MONEY,
    ADD CUST_DESP_GERAIS DMN_MONEY,
    ADD CUST_DESP_ADM DMN_MONEY,
    ADD CUST_COMISSAO DMN_MONEY,
    ADD CUST_IMPOSTO DMN_MONEY,
    ADD FI_RET_FINANC DMN_MONEY,
    ADD FI_RET_PLANO DMN_MONEY;

